ALTER TABLE clients
  ADD COLUMN IF NOT EXISTS document_number VARCHAR(50),
  ADD COLUMN IF NOT EXISTS birth_date DATE,
  ADD COLUMN IF NOT EXISTS nationality VARCHAR(100),
  ADD COLUMN IF NOT EXISTS address_street VARCHAR(255),
  ADD COLUMN IF NOT EXISTS address_neighborhood VARCHAR(255),
  ADD COLUMN IF NOT EXISTS address_postal_code VARCHAR(20),
  ADD COLUMN IF NOT EXISTS address_city VARCHAR(100),
  ADD COLUMN IF NOT EXISTS address_state VARCHAR(100),
  ADD COLUMN IF NOT EXISTS address_country VARCHAR(100),
  ADD COLUMN IF NOT EXISTS vehicle_brand VARCHAR(100),
  ADD COLUMN IF NOT EXISTS vehicle_model VARCHAR(100),
  ADD COLUMN IF NOT EXISTS vehicle_plate VARCHAR(20);
